
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: stagging
  labels:
    app: spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
      - name: spring
        image: 807410046616.dkr.ecr.us-east-1.amazonaws.com/java-ecr:latest
        ports:
        - containerPort: 8080

